### DISCUSSION TITLE
Enforce Branch Name Conventions

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#220] [Automation Example Bounties]
Enforce specific naming conventions for PR branches.

Conditions (all must be true)

* The incoming branch name is missing a required prefix or fails to match a specified regex pattern. 
* The branch name is not listed in the ignore list.

Automation Actions:
* Post a comment explaining the branch name requirements.
* Apply a red label: `❗ Incorrect Branch Name`
* Close the PR.

Use this custom expression:
```
branch:
  requiredPrefixes: ['feature', 'stable', 'fix']

  # This matches Jira ticket naming conventions, modify the regex to suit your project
  branchRegex: '\b[A-Za-z]+-\d+\b'

  ignoreList: [ 'development', 'staging' ]
```
