### DISCUSSION TITLE
Issue Tracking Use Cases

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#253] [Automation Example Bounties]
# Automatic Issue Tracker Links
Automation Name: comment_issue_tracker

Post a comment that provides a link to the associated resource in your issue tracker, such as Jira, Azure Boards, Shortcut, Asana, and more.

Conditions (all must be true):

* The PR contains a reference to project tracking tickets in the title or branch name. See the example comments to learn how to switch between the two.

Automation Actions

* Post a comment that provides a link to the issue.
  * This PR references [{{ jira.id }}]({{ jira.url }})

# Label Missing Issue Tracker Info
Automation Name: label_missing_info_tracker

Label PRs that lack a reference to a project tracker issue (Jira, Azure Boards, Shortcut, Asana) in the PR title or description.

Conditions (all must be true):

* The PR lacks a project tracker ticket number in the title, or a link to a project tracker resource in the PR description.

Automation Actions

* Apply a `⚠️ Missing Project Tracker` label.
* Post a comment explaining that the PR author must provide a refernce to the associated project tracker resource.
  * Please provide a link to the associated resource in your team's project tracker.

# Additional Notes
Most of the challenge of this proposal is figuring out how the third-party tools structure the URLs for their issue trackers, and coming up with regex that would detect the references.

Use this custom expression for the first example and create alternative versions of it for Asana, Azure Boards, and Shortcut.
```
jira:
    # Alternatively, you can use branch.name instead of pr.title in the next line.
    id: {{ pr.title | includes(regex=r/\b[A-Za-z]+-\d+\b/) }}
    url: https://example.atlassian.net/browse/{{ jira.id }}
```
[Use this Jira example](https://docs.gitstream.cm/integrations/jira/) as a starting point for the label missing issue tracker info example, and design it so that users can easily configure it for their provider.
