### DISCUSSION TITLE
Name Enforcement Use Cases

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#254] [Automation Example Bounties]
# Enforce Branch Name Policy

Automation Name: enforce_branch_name

Use regex to enforce specific branch name requirements.

Conditions (all must be true)

* The incoming branch name is missing a required prefix or fails to match a specified regex pattern. 
* The incoming branch name is not listed in the ignore list.

Automation Actions:
* Post a comment explaining the branch name requirements.
  * Incoming PRs must include one of the required prefixes: {{ INSERT REFERENCE HERE }}. , and must match the following regex: {{ branch.requiredPrefixes }}.
* Apply a red label: `❗ Incorrect Branch Name`
* Close the PR.

Use this custom expression:
```
branch:
  requiredPrefixes: ['feature', 'stable', 'fix']

  # This matches Jira ticket naming conventions, modify the regex to suit your project
  branchRegex: '\b[A-Za-z]+-\d+\b'

  ignoreList: [ 'development', 'staging' ]
```

# Enforce PR Title Name Policy
Automation Name: enforce_pr_title

Use regex to enforce specific PR title name requirements.

Conditions (all must be true):

* The PR fails to follow a predefined semantic release format: 

Automation Actions

* Request changes and post a comment explaining why.

Note to author: Emulate the behavior of this GitHub Action, specifically the title format it enforces: https://github.com/marketplace/actions/semantic-release-pr-title-check

Here is the message to post:
```
All PRs must be titled according to our semantic naming policy: `<type>(<scope>): <short summary>`

Type must be one of the following:

* build
* ci 
* docs
* feature
* fix

Scope must be one of the following:

* common
* core
* elements
* forms
* http

```
