### DISCUSSION TITLE
Review Assignment Use Cases

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#255] [Automation Example Bounties]
# Team-Based Review Policies

Assign PR reviewers based on the author's membership in specific teams.

Automation Name: review_{{ teams.name }}_team

Conditions (all must be true):

* The author is a member of one of the teams specified in the `teams` custom expression.

Automation Actions:

* Require a additional reviewers based on definitions for each individual team.
* Automatically assign that team as a reviewer.

Use the following custom expression in a similar manner as [this example](https://docs.gitstream.cm/automations/change-deprecated-components/).
```
teams:
    - name: ui-team
        requiredReviews: 2
    - name: mobile-team
        requiredReviewers: 4
```

# Require Additional Reviewers By Branch

Require a specific number of reviews based on branch names.

Note to author: the first example will need to use the `branch.name` context variable and the second example will need to use the `pr.target` context variable.

## By Source Branch
Automation Name: require_additional_reviewers_branch

Conditions (all must be true):

* The PR source branch name is prefixed with one of the keywords specified in the `branches` custom expression.

Automation Actions:

* Require a specific number of reviewers that's specific to the keyword

Use the following custom expression in a similar manner as [this example](https://docs.gitstream.cm/automations/change-deprecated-components/). The automation should look specifically for prefixes to the branch name (i.e. the first few letters of the name, followed by a dash)
```
branches:
    - prefix: ABC
        requiredReviews: 2
    - prefix: XYZ
        requiredReviewers: 4
```

## By Destination Branch
Automation Name: require_additional_reviewers_branch

Conditions (all must be true):

* The PR target branch name is prefixed with one of the keywords specified in the `branches` custom expression.

Automation Actions:

* Require a specific number of reviewers that's specific to the keyword

Use the following custom expression in a similar manner as [this example](https://docs.gitstream.cm/automations/change-deprecated-components/). The automation should look specifically for prefixes to the branch name (i.e. the first few letters of the name, followed by a dash)
```
branches:
    - prefix: ABC
        requiredReviews: 2
    - prefix: XYZ
        requiredReviewers: 4
```
