### DISCUSSION TITLE
Label PRs by Code Changes

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#267] [Automation Example Bounties]
Label PRs with information about the portions of the code that has been changed.

Automation Name: label_pr_changes

Conditions (all must be true):
* The PR affects code in one or more specific directories or files

Automation Actions:
* Apply labels for each of the specific areas of the code base that indicates what percent of the PR changes affect that area.

Author Notes:
* The Automation should calculate what percent of the total lines changes are in each category. Labels should say `30% Area - Core` '40%  Mobile` etc.
* The automation should use a custom expression similar to what is listed below. 
```
area:
  - name: Core
    resources:
      - /src/core
      - /makefile
  - name: Mobile
    resources:
      - /mobile
```
