### DISCUSSION TITLE
Improve PR Label Modified Resources Example to show percents

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#277] [Automation Example Bounties]
Modify the following example to also show the percent of total lines changed in the PR that fall into each category. E.g. 40% Mobile, 40% Core, 10% Docs, etc.

```
# -*- mode: yaml -*-
manifest:
  version: 1.0

automations:
  {% for item in labels %}
  label_automations_{{ item.name }}:
      if:
        - {{ files | match(list=item.resources) | some}}
      run:
        - action: add-label@v1
          args:
            label: {{ item.name }}
   {% endfor %}

labels:
  - name: Core
    resources:
    - src/app
  - name: mobile
    resources:
    - src/android
    - src/ios
   - name: docs
    resources:
    - docs/
    - Readme.md
```

**Comment by vim-zz** [comment]
@BenLloydPearson should change this 
```
# add `| some`
{{ files | match(list=item.resources) | some }}
```

**Comment by BenLloydPearson** [comment]
```
automations:
  label_automations:
      if:
         - {{ files | match(term='src/app') | some }}
      run:
        - action: add-label@v1
          args:
            label: '{{ branch.diff.files_metadata | filter(attr='file', regex='r/src\/app/') | map(attr='additions') | sum }}% Core'
```
