### DISCUSSION TITLE
gitStream Slash Commands

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#346] [Automation Example Bounties]
# Slash Commands with gitStream

This automation enables the following slash commands within your GitHub repo:
* Assign Reviewers - `/gitstream assign(user1, user2)` - Assign all users listed in the parenthesis.
* Suggest Code Experts - `/gitstream suggest-experts` - Trigger gitStream's explain code experts functionality.
* Close the PR - `/gitStream close` - Close the PR
* Dispatch GitHub Action Workflows for a PR - `/gitstream dispatch(workflow1, workflow2)` - Dispatch the specified workflows for this PR.
* Slash Command Help - `/gitstream help` - Post a comment that lists and describes all of the available gitStream slash commands.
* Incorrect gitStream Slash Command - Any invalid `/gitstream` command. - Post a comment that lists and describes all of the available slash commands

The slash commands should be implemented like this:
```
slashCommands:
  - name:  'Auto Assign Reviewer'
    command: '/gitstream auto-assign`
    description: 'Auto assign code reviewers.'
    actions:
      - action: add-reviewers@v1
        args:
          reviewers: {{ repo | codeExperts(gt=10) }}
```
