### DISCUSSION TITLE
Filter Code Reviewers Based on Team

### DISCUSSION THREAD

**Discussion by BenLloydPearson** [linear-b/gitstream#416] [Suggest a New gitStream Plugin]
Copied from #25 
## Overview

Is your feature request related to a problem? Please describe.

As an organization, we have multiple GitHub teams that are responsible for various repositories. These teams are not necessarily fixed, so members split out into new teams and so forth. We handle this in technical terms by placing them on new GH teams.

The issue is that they are still contributors to the codebase, and they're still a part of the organization, which means that they'll likely to be assigned as code reviewers for teams they're no longer part of. Today's solution needs us to manually map their GH users to "null", but that means we have to go through our repositories and maintain that list. This can quickly become tedious when one works with a solution that has a ton of repositories while allowing teams to be a little dynamic.

Describe the solution you'd like

I would like to be able to filter reviewers based on their team.

Describe alternatives you've considered

Right now, the only other option I can think of is either to maintain the team member list for every repo, or have a script that updates every repo as time changes.

## Example Configs

```yaml
  the_right_reviewer:
    if:
      - true
    run:
      - action: add-comment@v1
        args:
          comment: |
            {{ repo | explainRankByGitBlame(gt=25) }}
      - action: add-reviewers@v1
        args:
          reviewers: {{ repo | rankByGitBlame(gt=25) }}
```

To then filter out people we need to do something like this:
```yaml
config:
  user_mapping:
    - 'user that is part of team': 'atomfinger'
    - 'user that is no longer in team': null
```

## Example usage

`reviewers: {{ repo | rankByGitBlame(gt=25) | filterUsersOf(['Team A']) }}`

**Comment by vim-zz** [comment]
It might require accessing GitHub to get the list of users that are in 'Team A', there is a plugin which can be used as reference that does that: https://github.com/linear-b/gitstream/tree/main/plugins/filters/getCodeowners 

When used, create a secret TOKEN, and add it to the workflow file, in GitHub:
```
jobs:
  gitStream:
    steps:
      - name: Evaluate Rules
        uses: linear-b/gitstream-github-action@v1
        env: 
          TOKEN: ${{ secrets.GITSTREAM_TOKEN }}
```
