### ISSUE TITLE
Trigger gitStream check on new or edited comment

### ISSUE THREAD

**Issue by vim-zz** [linear-b/gitstream#1]
**Describe the bug**

**To Reproduce**
1. Using this automation in a repo 

```
automations:
  PR_title_must_contain_jira_id:
    if:
      - {{ pr.general_comments | length == 0 }}
    run:
      - action: add-comment@v1 
        args:
          comment: |
            WELCOME!
```

2. Open a new PR
3. Add a comment using the GitHub web editor
4. gitStream doesn't trigger

**Expected behavior**
I expected gitStream to trigger and to add a comment `WELCOME` as a result

**Screenshots**
<img width="941" alt="Screenshot 2022-12-12 at 16 07 59" src="https://user-images.githubusercontent.com/50141/207096511-d91680c3-e703-4327-9621-7f52851f9dfa.png">

**Git provider**
GitHub cloud

**Additional context**
None
