### ISSUE TITLE
Mutually exclusive rules are both passing

### ISSUE THREAD

**Issue by emcdaniel-sungage** [linear-b/gitstream#11]
I'm having an issue with a workflow setup in which I'm trying to set the number of reviewers on a PR. Here's the gitstream file:

```
# -*- mode: yaml -*-

manifest:
  version: 1.0

config:
  ignore_files:
    - 'yarn.lock'
    - 'back-end/server/schema.prisma'
    - 'back-end/server/schema.graphql'
    - 'shared/graphql/generated-types.ts'
is:
  small_pr: '{ branch | estimatedReviewTime <= 5 and files | length <= 20 }'
  medium_or_large_pr: '{ branch | estimatedReviewTime > 5 or files | length > 20 }'

automations:
  single_reviewer:
    if:
      - '{ is.small_pr }'
    run:
      - action: set-required-approvals@v1
        args:
          approvals: 1
  multi_reviewer:
    if:
      - '{ is.medium_or_large_pr }'
    run:
      - action: set-required-approvals@v1
        args:
          approvals: 2
```

This PR with only 1 file and only a few lines of code removed still requires 2 approvals.
![CleanShot 2023-01-17 at 11 10 26](https://user-images.githubusercontent.com/95384474/212951807-8b0d7fc7-ac8e-4eb6-865f-285f990e7177.png)

Looking into the logs of the run, under the Evaluate Rules section, I see the following, which shows that both mutually exclusive rules have passed:

```
{
  "automations": 
  { 
    "gitstream/single_reviewer": 
    { 
      "if": [
        { 
          "passed": "{ is.small_pr }"
        }
      ], 
      "run": 
      [
        { "action": "set-required-approvals@v1", "args": { "approvals": 1 } }
      ], 
      "passed": true 
    },
    "gitstream/multi_reviewer":
    { 
      "if": [
        { "passed": "{ is.medium_or_large_pr }" }
      ], 
      "run": [
        { "action": "set-required-approvals@v1", "args": { "approvals": 2 } }
      ], 
      "passed": true 
    } 
  }
}
```

Shoudn't only one of them pass, given my config? Or is there something wrong with the way I have setup the `is:` checks?
