### ISSUE TITLE
Multiple comments from gitstream-cm instead of deleting old ones

### ISSUE THREAD

**Issue by deiga** [linear-b/gitstream#113]
**Describe the bug**

Gitstream bot is spamming some of our PRs with multiple comments seemingly after Review comments. It never removes or updates the old comments which makes the timeline difficult to read.
**To Reproduce**

1. The `.cm` automation file:
```
# -*- mode: yaml -*-
manifest:
  version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}
  code_experts:
    if:
      - true
    run:
      - action: add-comment@v1
        args:
          comment: |
            {{ repo | explainCodeExperts(gt=10) }}
  {% for item in deprecated %}
  catch_deprecated_components_{{ loop.index }}:
    if:
      - {{ source.diff.files | matchDiffLines(regex=item.regex) | some }}
    run:
      - action: add-label@v1
        args:
          label: 'deprecated-component'
          color: '#FF0000'
      - action: request-changes@v1
        args:
          comment: |
            Usage `{{ item.old }}` is deprecated please use `{{ item.new }}` instead
  {% endfor %}

calc:
  etr: {{ branch | estimatedReviewTime }}

deprecated:
  - regex: r/translateByKey/
    old: translateByKey
    new: formatMessage
  - regex: r/addStyles/
    old: addStyles
    new: SASS in a separate file ([Component name].scss)
  - regex: r/addNotificationsFromQuery/
    old: addNotificationsFromQuery
    new: UI/hooks/useGetNotificationsFromQuery
  - regex: r/from 'enzyme'/
    old: Enzyme
    new: testing-utils/testingLibrary
```
3. [The PR URL (as it contains the repo and PR identifiers)](https://github.com/amboss-mededu/ui-amboss/pull/5277)
4. Describe your PR relevant content: Changes to tests and added new deprecation warning to CM config
5. Add relevant commit SHA

**Expected behavior**

I'd expect GitStream to update it's first comment whenever it runs

**Screenshots**

All posted comments from the bot
![Screenshot 2023-04-20 at 12 28 32](https://user-images.githubusercontent.com/27202/233323259-c038c39a-fcb0-404d-a8d4-a59de885b051.png)
![Screenshot 2023-04-20 at 12 28 49](https://user-images.githubusercontent.com/27202/233323339-bd390d2d-be7e-4d65-bc69-fb0967f44e11.png)
![Screenshot 2023-04-20 at 12 29 14](https://user-images.githubusercontent.com/27202/233323453-b8624f6a-643b-4d39-a44e-99cc4abfa77f.png)
![Screenshot 2023-04-20 at 12 29 24](https://user-images.githubusercontent.com/27202/233323494-ede1d016-ee78-427e-b789-fb6fb0c10d00.png)
![Screenshot 2023-04-20 at 12 29 37](https://user-images.githubusercontent.com/27202/233323559-be0ee9f7-3207-4927-addf-0a8012049ef0.png)
![Screenshot 2023-04-20 at 12 30 02](https://user-images.githubusercontent.com/27202/233323660-f334cf41-0306-4a04-a30b-1e85b5a5914b.png)
![Screenshot 2023-04-20 at 12 30 20](https://user-images.githubusercontent.com/27202/233323741-6eaf0878-b109-4055-b320-c0a3ed05e6c2.png)
