### ISSUE TITLE
matchDiffLines also matches removed lines

### ISSUE THREAD

**Issue by deiga** [linear-b/gitstream#117]
**Describe the bug**

Your example `catch_deprecated_component` (linked below) uses `matchDiffLines` to check a regex and when true mark the PR as using a deprecated component. 
This function seems also to match **removed** lines in the Diff, which erroneously marks PRs that cleanup deprecated components.

**To Reproduce**

1. The `.cm` automation file
```
# -*- mode: yaml -*-
manifest:
  version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}
  {% for item in deprecated %}
  catch_deprecated_components_{{ loop.index }}:
    if:
      - {{ source.diff.files | matchDiffLines(regex=item.regex) | some }}
    run:
      - action: add-label@v1
        args:
          label: 'deprecated-component'
          color: '#FF0000'
      - action: add-comment@v1
        args:
          comment: |
            Usage `{{ item.old }}` is deprecated please use `{{ item.new }}` instead
  {% endfor %}

calc:
  etr: {{ branch | estimatedReviewTime }}

deprecated:
  - regex: r/translateByKey\(/
    old: translateByKey
    new: formatMessage
  - regex: r/addStyles\(/
    old: addStyles
    new: SASS in a separate file ([Component name].scss)
  - regex: r/addNotificationsFromQuery/
    old: addNotificationsFromQuery
    new: UI/hooks/useGetNotificationsFromQuery
  - regex: r/from 'enzyme'/
    old: Enzyme
    new: testing-utils/testingLibrary

```
2. The PR URL (as it contains the repo and PR identifiers): https://github.com/amboss-mededu/ui-amboss/pull/5281
3. Describe your PR relevant content: Replace deprecated function `translateByKey`

**Expected behavior**

We expected that this check only reacts to **additions** and not deletions

**Screenshots**

![Screenshot 2023-04-21 at 09 52 26](https://user-images.githubusercontent.com/27202/233562570-58b00531-a1ce-43dc-9718-1dee04ac8e5e.png)

**Additional context**

```
{% for item in deprecated %}
  # Automation names must be unique, so this adds an iterator index to each instance
  catch_deprecated_components_{{ loop.index }}:
    # Triggered when any of the modified files use a deprecated component
    if:
      - {{ source.diff.files | matchDiffLines(regex=item.regex) | some }}
    # Apply a deprecated-component label, request changes, and post a comment with an explanation.
    run:
      - action: add-label@v1
        args:
          label: 'deprecated-component'
          color: '#FF0000'
      - action: request-changes@v1
        args:
          comment: |
            `{{ item.old }}` component is deprecated, use `{{ item.new }}` instead
  {% endfor %}
```

**Comment by vim-zz** [comment]
@deiga to catch only added lines (which is what you want), you shoule add `^[+].*` at the start of the regex, so for example: 

```
deprecated:
  - regex: r/^[+].*translateByKey\(/
    old: translateByKey
    new: formatMessage
  - regex: r/^[+].*addStyles\(/
    old: addStyles
    new: SASS in a separate file ([Component name].scss)
  - regex: r/^[+].*addNotificationsFromQuery/
    old: addNotificationsFromQuery
    new: UI/hooks/useGetNotificationsFromQuery
  - regex: r/^[+].*from 'enzyme'/
    old: Enzyme
    new: testing-utils/testingLibrary
```

This will work as the diff itself contains `+` at the begining of every added line and `-` at the begining of every removed line
