### ISSUE TITLE
rule-parser: Regression with `match()` function (`(unknown path) TypeError: arr.map is not a function`), exit code 60

### ISSUE THREAD

**Issue by mishagp** [linear-b/gitstream#13]
**Describe the bug**

Since 12/30/22 at 12:49pm CST the gitStream action has consistently failed with the following error message: `(unknown path) TypeError: arr.map is not a function` using a `.cm` config which hasn't changed since 12/6/22.

**To Reproduce**

Use the `match()` function with any input (string, array, or regex) in your `.cm` config file, see included config below.

The action succeeds after removing all uses of `match()`. We had to remove our `no_tests` automation and supplement `safe_changes` by using `isTests()` in the below config.

**Screenshots**

![image](https://user-images.githubusercontent.com/6118330/213752525-8c6fcccb-cae1-459f-9d61-1bd4fd195310.png)

```
ERROR:  Template render error: (unknown path)
  TypeError: arr.map is not a function
    at Object._prettifyError (/node_modules/nunjucks/src/lib.js:36:11)
    at /node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:36:3)
    at Template.render (/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/node_modules/nunjucks/src/environment.js:380:17)
    at /node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1259:45
    at new Promise (<anonymous>)
    at _loop$ (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:1258:32)
    at tryCatch (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:96:17)
    at Generator._invoke (/node_modules/@linearb/gitstream-rule-parser/dist/gitstream-rule-parser.cjs.development.js:76:24)
Error: (unknown path)
  TypeError: arr.map is not a function
Error: Process completed with exit code 60.
```

**Additional context**

Original config:
```yaml
# -*- mode: yaml -*-

manifest:
    version: 1.0

automations:
    estimated_time_to_review:
        if:
            - true
        run:
            -   action: add-label@v1
                args:
                    label: "{{ calc.etr }} min review"
                    color: {{'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853')}}

    safe_changes:
        if:
            - {{is.formatting or is.docs or is.tests}}
        run:
            -   action: add-label@v1
                args:
                    label: 'safe-changes'
            -   action: approve@v1

    no_tests:
        if:
            - {{is.formatting or is.docs | nope}}
            - {{files | match(regex=r/tests\//) | nope}}
        run:
            -   action: add-label@v1
                args:
                    label: 'missing-tests'
                    color: '#E94637'

calc:
    etr: {{branch | estimatedReviewTime}}
is:
    formatting: {{source.diff.files | isFormattingChange}}
    docs: {{files | allDocs}}
    tests: {{files | match(regex=r/tests\//) | every}}
```

**Side note**

I noticed that there were a few discrepancies on regex syntax and escaping characters in some spots on the gitStream docs.
![image](https://user-images.githubusercontent.com/6118330/213753732-f488f20e-edfa-4cb8-85bd-a0bb146ff8ea.png)
![image](https://user-images.githubusercontent.com/6118330/213753782-282c5fb8-7995-4a8a-aa29-8d77b57c1958.png)
![image](https://user-images.githubusercontent.com/6118330/213753805-22539829-6364-4f28-8f6b-cc2d6569811c.png)
