### ISSUE TITLE
Gitlab add-reviewers@v1 not assigning reviewers

### ISSUE THREAD

**Issue by struct78** [linear-b/gitstream#145]
**Describe the bug**

I've got most of my gitstream automations working just fine, however when I try to assign reviewers it fails silently every time. My goal is to basically assign all maintainers who aren't the pr.author, e.g.

```
reviewers: {{ maintainers  | filter(term=pr.author) | nope }}
```

I've tried `rankByGitBlame` and `rankByGitActivity` as well, with no success.

**To Reproduce**

Minimal reproduction:

```
manifest:
  version: 1.0

automations:
  assign_reviewers:
    if:
      - true
    run:
      - action: add-reviewers@v1
        args:
          reviewers: {{ maintainers }}
          
maintainers:
  - 'person-a'
  - 'PersonB'
  - 'DeveloperC'
 ```

**Expected behavior**

I would expect the 3 maintainers to be added as reviewers.

**Additional context**

We are using Gitlab cloud.
