### ISSUE TITLE
gitstream job taking hours and hours to run, no information about why

### ISSUE THREAD

**Issue by ToddBradley** [linear-b/gitstream#15]
**Describe the bug**

I made a change to my project's `.cm/gitstream.cm` file, and created a PR to try it out. I think it should be running dry run mode, but I can't tell. 17 hours later, the check still hasn't completed, and there is no log output to give me any clue about why.

The only feedback I see in the PR is this:

```
gitStream.cm / gitStream.cm
Started 16h 59m 5s ago
[View more details on gitStream.cm](https://docs.gitstream.cm/examples/)

Viewing more details doesn't really help, because it just leads me to the example document.

And there are no log messages at all to tell me what has or hasn't happened in the past 17 hours.

```

**To Reproduce**

First, here is my .cm file (with comments stripped, for brevity):

```yaml
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}

  safe_changes:
    if:
      - {{ is.formatting or is.docs or is.renovate_config }}
    run:
      - action: add-label@v1
        args:
          label: 'safe-changes'
      - action: approve@v1

  github_teams_changes:
    if:
      - {{ files | match(regex=r/\.github\/teams.yml/) | every }}
    run:
      - action: add-label@v1
        args:
          label: 'safe-changes'
      - action: approve@v1

calc:
  etr: {{ branch | estimatedReviewTime }}
is:
  formatting: {{ source.diff.files | isFormattingChange }}
  docs: {{ files | match(regex=r/\.md$|\.rst$/) | every }}
  renovate_config: {{ files | match(regex=r/renovate.json5/) | every }}

```

The PR URL: (removed for security reasons)

Describe your PR relevant content: This PR has two changes. First is the `.cm` file shown above. Second is adding a file called `documentation/source/bar.md` as a test. 

Add relevant commit SHA: I don't know how this will help you, because it's not a public repo, but the commit SHA is `464acdb4b7db3788b45cd2518e05eb0dcc6df114`

**Expected behavior**

I expected two things:

* gitstream should approve the PR
* gitstream should add dry run comments to the PR to explain what it's doing

**Screenshots**

<img width="272" alt="Screenshot 2023-01-26 at 9 01 16 AM" src="https://user-images.githubusercontent.com/6644581/214889784-3756b327-6ace-48cf-a0d5-fbba8edffa1c.png">

**Additional context**

(I can't think of anything relevant)
