### ISSUE TITLE
Marking requested change as resolved doesn't trigger a new gistream check

### ISSUE THREAD

**Issue by matthewparavati** [linear-b/gitstream#153]
**Describe the bug**

We have an automation to add a "changes requested" label if a change is requested on a PR. When the requested change is marked as resolved, gitstream is _not_ running a new check so the "changes requested" label is never being removed

**To Reproduce**
This is our current automation to add the label

```
requested_changes:
    if:
      - {{ pr.status == 'open' }}
      - {{ pr.requested_changes | length > 0 }}
    run:
      - action: add-label@v1
        args:
          label: '🚨 Changes requested'
          color: '#EC560D'
```

**Expected behavior**

After the requested change is marked as resolved, then gitstream runs a new check and the "Changes requested" label is removed

**Screenshots**
<img width="1248" alt="Screenshot 2023-05-10 at 12 43 31" src="https://github.com/linear-b/gitstream/assets/12176557/d7b0b56a-e454-4ed1-9b7f-e82873005265">

**Additional context**
Addiitonal background info in #74
