### ISSUE TITLE
gitstream.cm failing: Failed to get PR context

### ISSUE THREAD

**Issue by sophieher** [linear-b/gitstream#16]
**Describe the bug**

Intermittently seeing this issue on one repo.

**To Reproduce**

1. The `.cm` automation file
  no real change
  ```
 # -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}

  safe_changes:
    if:
      - {{ is.formatting or is.docs or is.tests }}
    run:
      - action: add-label@v1
        args:
          label: 'safe-changes'
calc:
  etr: {{ branch | estimatedReviewTime }}
is:
  formatting: {{ source.diff.files | isFormattingChange }}
  docs: {{ files | allDocs }}
  tests: {{ files | allTests }}
```
2. Describe your PR relevant content - this happens on some PRs and not others, and only in this repo. we have other repos with the same gitream.cm file and the checks have no issues

**Expected behavior**

To have consistent runs.

**Output**

This is copied output from the action that failed with the mentioned error. In the Evaluate Rules stage.
```
...
From https://github.com/<org>/<repo>
 * branch              dev        -> FETCH_HEAD
 * [new branch]        dev        -> origin/dev
Switched to a new branch 'dev'
branch 'dev' set up to track 'origin/dev'.
Switched to branch 'branch-to-merge'
Your branch is up to date with 'origin/branch-to-merge'.
From https://github.com/<org>/<repo>
 * branch              branch-to-merge -> FETCH_HEAD

latest: Pulling from gitstream/rules-engine
59bf1c3509f3: Pulling fs layer
b616ac4a64bf: Pulling fs layer
3b9e1e8ab9ce: Pulling fs layer
3507ddbf3909: Pulling fs layer
f0ad28c522fc: Pulling fs layer
893f905b8c89: Pulling fs layer
2f083e44ca6f: Pulling fs layer
91b037256d6e: Pulling fs layer
d51b06a31021: Pulling fs layer
4ecd0e153a1f: Pulling fs layer
3507ddbf3909: Waiting
2f083e44ca6f: Waiting
f0ad28c[522](https://github.com/<org>/<repo>/actions/runs/4046369097/jobs/6959067838#step:2:535)fc: Waiting
91b037256d6e: Waiting
d51b06a31021: Waiting
893f905b8c89: Waiting
4ecd0e153a1f: Waiting
59bf1c3509f3: Verifying Checksum
59bf1c3509f3: Download complete
3b9e1e8ab9ce: Verifying Checksum
3b9e1e8ab9ce: Download complete
3507ddbf3909: Verifying Checksum
3507ddbf3909: Download complete
893f905b8c89: Verifying Checksum
893f905b8c89: Download complete
b616ac4a64bf: Verifying Checksum
b616ac4a64bf: Download complete
f0ad28c522fc: Verifying Checksum
f0ad28c522fc: Download complete
91b037256d6e: Verifying Checksum
91b037256d6e: Download complete
59bf1c3509f3: Pull complete
4ecd0e153a1f: Verifying Checksum
4ecd0e153a1f: Download complete
2f083e44ca6f: Verifying Checksum
2f083e44ca6f: Download complete
d51b06a31021: Verifying Checksum
d51b06a31021: Download complete
b616ac4a64bf: Pull complete
3b9e1e8ab9ce: Pull complete
3507ddbf3909: Pull complete
f0ad28c522fc: Pull complete
893f905b8c89: Pull complete
2f083e44ca6f: Pull complete
91b037256d6e: Pull complete
d51b06a31021: Pull complete
4ecd0e153a1f: Pull complete
Digest: sha256:c0b9f90ae380846d33e7fd077f6ad0b3058a8de86d64b33fb8bc67053cf81abf
Status: Downloaded newer image for gitstream/rules-engine:latest
docker.io/gitstream/rules-engine:latest

> gitstream-rules-engine@1.0.0 start
> node src/app.js

Running tag v1.91
Switched to branch 'dev'
Switched to branch 'branch-to-merge'
grep: unrecognized option: global
BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A|B|C N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...

Search for PATTERN in FILEs (or stdin)

	-H	Add 'filename:' prefix
	-h	Do not add 'filename:' prefix
	-n	Add 'line_no:' prefix
	-l	Show only names of files that match
	-L	Show only names of files that don't match
	-c	Show only count of matching lines
	-o	Show only the matching part of line
	-q	Quiet. Return 0 if PATTERN is found, 1 otherwise
	-v	Select non-matching lines
	-s	Suppress open and read errors
	-r	Recurse
	-R	Recurse and dereference symlinks
	-i	Ignore case
	-w	Match whole words only
	-x	Match whole lines only
	-F	PATTERN is a literal (not regexp)
	-E	PATTERN is an extended regexp
	-m N	Match up to N times per file
	-A N	Print N lines of trailing context
	-B N	Print N lines of leading context
	-C N	Same as '-A N -B N'
	-e PTRN	Pattern to match
	-f FILE	Read pattern from file
Error: Failed getting PR context.
Error: Process completed with exit code 40.
```

**Screenshot**
![Screen Shot 2023-01-30 at 11 55 19 AM](https://user-images.githubusercontent.com/2704209/215555949-6acbcd46-3125-4a53-af0d-adb60c97fdc7.png)

**Additional context**

all failures are the same, `Failed to get PR context.`

**Comment by vim-zz** [comment]
Hi @sophieher the `.cm` file is not formatted correctly - This is the fixed version:

```
# -*- mode: yaml -*-

manifest:
version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}

  safe_changes:
    if:
      - {{ is.formatting or is.docs or is.tests }}
    run:
      - action: add-label@v1
        args:
          label: 'safe-changes'
calc:
  etr: {{ branch | estimatedReviewTime }}
is:
  formatting: {{ source.diff.files | isFormattingChange }}
  docs: {{ files | allDocs }}
  tests: {{ files | allTests }}
```
