### ISSUE TITLE
New Example: Approve PRs with changes to Swimm files only

### ISSUE THREAD

**Issue by Omerr** [linear-b/gitstream#166]
## Proposed Name
Approve PRs with changes to Swimm files only

## Description
[Swimm](https://swimm.io) is a knowledge management tool for code.

It should be easy to contribute to documentation. It thus makes sense not to block PRs for changes to Swimm files only.

## Audience
Any engineer who uses Swimm.

## Technical Description

Conditions (all must be true):
* Only files within the `.swm` folder changed

Automation Actions:
* Approve PR
* Add a label
* Add a comment

## Screenshot
![image](https://github.com/linear-b/gitstream/assets/52040016/0e663253-7214-4af3-9251-0bfadf62a120)

## Other

Do you want us to recognize your GitHub username on the automation library page?
Sure thing :)

Have you tested this example to confirm it performs as expected?
Yes

## Appendix
```
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  safe_changes:
    # Triggered for any changes to formatting, documentation, or tests
    if:
      - {{ files | match(regex=r/\.swm\//) | every }}
    # Apply a safe change label, approve the PR and explain why in a comment.
    run: 
      - action: add-label@v1
        args:
          label: 'swimm-docs-only'
      - action: approve@v1
      - action: add-comment@v1
        args:
          comment: |
            This PR is considered a safe change as it only affects Swimm Docs. It has been automatically approved.
```
