### ISSUE TITLE
Support regex for deprecated apis

### ISSUE THREAD

**Issue by MishaKav** [linear-b/gitstream#17]
**Describe the bug**

Please add/fix support for `regex` in deprecated apis.
I attached the example when the **first line of `regex` is working**, but the second is not working.

**To Reproduce**

```YAML
automations:
  {% for item in deprecated %}
  catch_deprecated_components_{{ loop.index }}:
    if:
      - {{ source.diff.files | matchDiffLines(regex=item.regex) | some }}
    run:
      - action: add-label@v1
        args:
          label: 'deprecated-component'
      - action: request-changes@v1
        args:
          comment: |
            `{{ item.regex }}` is deprecated, use `EventType` from `constants.py/constants.ts[js]`
  {% endfor %}

deprecated:
  - regex: r/^[+].*Types.EVENT_REQUESTED/
  - regex: r/^[+].*eventRequested\/v1/
```

**Expected behavior**

the current snippet should run as valid.

**Screenshots**

![image](https://user-images.githubusercontent.com/289035/217203225-8a6acbe6-1ca0-4f33-9265-cd757cc126f1.png)
