### ISSUE TITLE
Re-trigger on title changes

### ISSUE THREAD

**Issue by kg-currenxie** [linear-b/gitstream#18]
**Is your feature request related to a problem? Please describe.**
```
  format_title_conventional_commits:
    if:
      - {{ [ pr.title ] | match(regex=r/^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$/, ignoreWhiteSpaces=false) | nope }}
    run:
      - action: request-changes@v1
        args:
          comment: |
            PR title should match conventional commit format! https://www.conventionalcommits.org
            ex: `feat: [sc-1234] A shiny new feature`
```

![image](https://user-images.githubusercontent.com/48229166/217418614-e7722e1e-6ab4-41ea-b988-d3e4112b8f71.png)

**Describe the solution you'd like**
Would be nice for gitStream to re-run and pass it's check

**Additional context**
Now we manually have to dismiss its change request
