### ISSUE TITLE
`unless_reviewers_set: true` does not work when teams are assigned as reviewer

### ISSUE THREAD

**Issue by groyoh** [linear-b/gitstream#185]
**Describe the bug**

The `unless_reviewers_set: true` argument of the `add-reviewers@v1` action seems to work only when the PR already has individual reviewers and not when it already has teams assigned as reviewers.

If this is the expected behaviour, then the argument documentation is lacking a note/warning.

**To Reproduce**

1. The `.cm` automation file: https://github.com/happydemics/gitstream-bug-report/blob/main/.cm/gitstream.cm
2. The PR URL (as it contains the repo and PR identifiers): https://github.com/happydemics/gitstream-bug-report/pull/2
3. I added a team as reviewer

**Expected behavior**

I would expect no reviewer to be assigned when the PR already has an team assigned as reviewer and `unless_reviewers_set` is set to `true`. For example, the same action worked on this PR as it includes an individual reviewer: https://github.com/happydemics/gitstream-bug-report/pull/1.

**Screenshots**

**Additional context**

For now, I guess we can work around by relying on `if` and `pr.reviewers` context.

**Comment by vim-zz** [comment]
Thank you @groyoh this looks like a bug

**Comment by vim-zz** [comment]
@groyoh please check again, should be good now

**Comment by groyoh** [comment]
Will do. Thanks @vim-zz!

**Comment by mattshaffer11** [comment]
@vim-zz I am running into a similar issue where I am using the action `add-reviewers@v1` example from this [following post](https://linearb.io/blog/top-code-review-automation-for-open-source-communities#welcome-first-time-contributors). My automation file essentially looks like:

```yaml
# -*- mode: yaml -*-
manifest:
  version: 1.0
automations:
  # Help newcomers find mentors to guide them.
  first_time_contributor:
    # If the PR author made their first contribution on the current day
    if:
      - {{ repo.author_age < 42 and (repo.age - repo.author_age) >= 42 }}
    # 1. Add reviewers from the team `my_organization/mentors`. Replace this string to match your organization and team
    # 2. Apply a new-contributor label.
    # 3 Post a comment that explains the next steps.
    run:
      - action: add-reviewers@v1
        args:
          reviewers: [my_organization/mentors] # <- Individual contributors do not have an issue but a team does
      - action : add-comment@v1
        args:
          comment: |
            Hello {{ pr.author }} 👋 Thanks for making your first PR, and welcome to our project!
            Our mentor team has automatically been assigned to review this PR and guide you through the process.
            Please reach out to that team if you have questions about the next steps.
```

I don't run into any issues with an individual assigned, but the teams doesn't seem to work. Any ideas of what could be going on?
