### ISSUE TITLE
GitStream bot emails became extremely noisy

### ISSUE THREAD

**Issue by innabelov75** [linear-b/gitstream#197]
In the past couple of weeks, I noticed that GitStream started producing too many email notifications. I get emails even when no actions were executed on a PR in GitHub, or when someone just left a comment on a PR. The notifications usually contain information about **Code experts**, so it looks like this one script is triggering the multiple emails. This started happening only recently, but became very annoying.

**Comment by vim-zz** [comment]
@innabelov75 thank you for the feedback, we are going to support `edit_in_place` for the `add-comment` action so it won't trigger after the first time. I will update once its available so you can change your CM file to use that

**Comment by tresat** [comment]
I'm seeing this as well, for example [here](https://github.com/gradle/gradle/pull/25126).

**Comment by pdfowler** [comment]
The `edit_in_place` will make all the difference in the world. FWIW, I'm getting begged to disable gitStream because of this.

**Comment by vim-zz** [comment]
we hear you!

**Comment by vim-zz** [comment]
We are working on it, hopefullt will be ready this week or the following one

**Comment by vim-zz** [comment]
We are working no a new action, I will update soon once its ready. Example usage: 

```
code_experts:
  if:
    - true
  run:
    - action: add-code-experts@v1 
      args:
        gt: 10
```

**Comment by vim-zz** [comment]
This is now released, to reduce noise and avoid notifications on any commit: 

1. remove your existing codeExperts autamation 
2. add this automation: 

```
automations:
  code_experts:
    if:
      - true
    run:
      - action: explain-code-experts@v1
        args:
          gt: 10
```

This automation shall edit the codeExperts comment whenever there are changes to the PR, without triggering a new comment.
