### ISSUE TITLE
add-reviewers hard limit?

### ISSUE THREAD

**Issue by struct78** [linear-b/gitstream#208]
Howdy,

We have a simple task that can add up to 3 reviewers from a static list, however we're noticing it's only ever assigning 2. Is there a way to up this limit?

This is our .cm/gitstream.cm

```
manifest:
  version: 1.0

automations:
  assign_reviewers:
    if:
      - true
    run:
      - action: add-reviewers@v1
        args:
          reviewers: {{ maintainers | reject(term=pr.author) }}  
    
maintainers:
  - PersonA
  - PersonB
  - PersonC
  - PersonD
```
