### ISSUE TITLE
Label additions through `add-label@v1` action, occur multiple times in automations, even if conditions should fail

### ISSUE THREAD

**Issue by yashsway** [linear-b/gitstream#214]
**Describe the bug**

An `add-label@v1` action in an automation seems to be running over and over, when it shouldn't as defined by the `if` conditions. (it removes and adds the label it is supposed to, over and over)

It's _very_ noisy in PRs in our organization at the moment.

**To Reproduce**

1. The `.cm` automation file
```yaml
# -*- mode: yaml -*-
# This configuration is for gitStream. To know more visit: https://docs.gitstream.cm/quick-start/
manifest:
  version: 1.0
automations:
  # Flag the author if an appropriate type label isn't present
  check_label_type:
    if:
      - {{ not (pr.labels | match(list=constants.labels.type) | some) }}
    run:
      - action: add-comment@v1
        args:
          comment: |
            You're missing a label to indicate what kind of change this PR encompasses overall. Choose one of: {{ constants.labels.type | dump | safe }}
  # Add appropriate label based on scope of changes
  add_label_scope_app_frontend_web:
    if:
      - {{ is.scope.apps.frontend_web }}
      - {{ pr.labels | match(term=constants.labels.scope.apps.frontend_web) | nope }}
    run:
      - action: add-label@v1
        args:
          label: "{{ constants.labels.scope.apps.frontend_web }}"
  add_label_scope_app_frontend_mobile:
    if:
      - {{ is.scope.apps.frontend_mobile }}
      - {{ pr.labels | match(term=constants.labels.scope.apps.frontend_mobile) | nope }}
    run:
      - action: add-label@v1
        args:
          label: "{{ constants.labels.scope.apps.frontend_mobile }}"
  add_label_scope_packages_common_components:
    if:
      - {{ is.scope.packages.common_components }}
      - {{ pr.labels | match(term=constants.labels.scope.packages.common_components) | nope }}
    run:
      - action: add-label@v1
        args:
          label: "{{ constants.labels.scope.packages.common_components }}"
  add_label_scope_packages_domain:
    if:
      - {{ is.scope.packages.domain }}
      - {{ pr.labels | match(term=constants.labels.scope.packages.domain) | nope }}
    run:
      - action: add-label@v1
        args:
          label: "{{ constants.labels.scope.packages.domain }}"
  add_label_scope_packages_formatters:
    if:
      - {{ is.scope.packages.formatters }}
      - {{ pr.labels | match(term=constants.labels.scope.packages.formatters) | nope }}
    run:
      - action: add-label@v1
        args:
          label: "{{ constants.labels.scope.packages.formatters }}"
  # Always, add a label that indicates how many minutes it will take to review the PR
  add_label_estimated_time_to_review:
    if:
      - {{ not is.author.dependabot }}
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.time_to_review }} min review"
          color: {{ 'E94637' if (calc.time_to_review >= 20) else ('FBBD10' if (calc.time_to_review >= 5) else '36A853') }}
  # If the PR changes are medium or large, then code experts will be assigned to review it
  assign_reviewers_code_experts:
    if:
      - {{ is.size.medium or is.size.large }}
      - {{ not is.author.dependabot }}
    # Identify the best experts to assign for review and post a comment that explains why
    # @see https://docs.gitstream.cm/filter-functions/#codeexperts
    run:
      - action: add-reviewers@v1
        args:
          reviewers: {{ repo | codeExperts(gt=5) | reject(list=constants.inactive_contributors) }}
          unless_reviewers_set: true
      - action: add-comment@v1
        args:
          comment: |
            {{ repo | explainCodeExperts(gt=5) }}
  # If the PR changes are small enough, then a group of reviewers will be assigned instead
  assign_reviewers_default_reviewer_group:
    if:
      - {{ is.size.small }}
    run:
      - action: add-reviewers@v1
        args:
          reviewers: {{ constants.default_frontend_group }}
      - action: add-comment@v1
        args:
          comment: |
            {{ repo | explainCodeExperts(gt=5) }}
  # Automatically approve changes to certain files
  safe_changes:
    if:
      - {{ files | match(list=['.cm/.gitstream.cm']) | every }}
    # approve the PR and explain why
    run: 
      - action: approve@v1
      - action: add-comment@v1
        args:
          comment: |
            This PR is considered a safe change and has been automatically approved.
# custom variables/expressions
calc:
  # high-level filter function to calculate the estimated review time 
  # @see https://docs.gitstream.cm/filter-functions/#estimatedreviewtime
  time_to_review: {{ branch | estimatedReviewTime }}
constants:
  default_frontend_group: ['OBFUSCATED']
  labels:
    type: ['feature / enhancement', 'bug', 'chore', 'refactor', 'documentation', 'RFC', 'dependencies']
    scope:
      apps:
        frontend_web: 'App: Frontend'
        frontend_mobile: 'App: Frontend Mobile'
      packages:
        common_components: 'Package: Common Components'
        domain: 'Package: Domain'
        formatters: 'Package: Formatters'
    admin: ['blocked', 'duplicate']
is:
  size:
    small: {{ branch.diff.size < 200 }}
    medium: {{ branch.diff.size >= 200 and branch.diff.size < 400 }}
    large: {{ branch.diff.size >= 400 }}
  author:
    # if the branch name and the branch author has the word 'dependabot' in it
    dependabot: {{ (branch.name | includes(term="dependabot")) and (branch.author | includes(term="dependabot")) }}
  scope:
    apps:
      frontend_web: {{ files | match(regex=r/apps\/COMPANY-frontend\//) | some }}
      frontend_mobile: {{ files | match(regex=r/apps\/frontend-mobile\//) | some }}
    packages:
      common_components: {{ files | match(regex=r/packages\/common-components\//) | some }}
      domain: {{ files | match(regex=r/packages\/domain\//) | some }}
      formatters: {{ files | match(regex=r/packages\/formatters\//) | some }}

```

2. The PR URL (as it contains the repo and PR identifiers) - ❌ can't provide this as the PR is in a private org repo.
4. Describe your PR relevant content ❌ nothing really relevant here - just standard PR changes are made on every commit
5. Add relevant commit SHA ❌ again, can't provide this as the PR is in a private org repo.

**Expected behavior**

I expect to have the appropriate missing labels only added once, depending on the diff of the branch through the following automations:

- add_label_scope_app_frontend_web
- add_label_scope_app_frontend_mobile
- add_label_scope_packages_common_components
- add_label_scope_packages_domain
- add_label_scope_packages_formatters

**Screenshots**
<img width="463" alt="image" src="https://github.com/linear-b/gitstream/assets/5233993/f62f8cb9-10af-4551-a41f-3a4b53c0c6dd">
---
<img width="903" alt="image" src="https://github.com/linear-b/gitstream/assets/5233993/d9ce8d94-f308-466a-b377-05893d0619da">

If you think the labels are getting added and removed based on the commit that just got pushed to the PR, it does not.

1. You can see here that this commit only had one change under `apps/COMPANY-frontend` so let's say it adds the label "App: Frontend"... but why would it add "Package: Domain"? The commit has no changes related to that.
<img width="813" alt="image" src="https://github.com/linear-b/gitstream/assets/5233993/27ba94b5-f58b-4719-9c1c-e0c4f1b1760f">

2. And with this commit, you can see changes were made under `apps/COMPANY-frontend`, but it removes the labels "App: Frontend" and "Package: Domain" instead. Say "Package: Domain" was valid to be removed because this commit didn't have changes to it... why would it remove "App: Frontend"?
<img width="909" alt="image" src="https://github.com/linear-b/gitstream/assets/5233993/33fc2112-5c66-4335-a919-ef91734569df">

**Additional context**
n/a

**Comment by vim-zz** [comment]
Hi @yashsway,

Thank you for the detailed report. gitStream is designed to manage labels for you, so you don't have to manually handle them. The issue you're experiencing seems to be due to the logic in your `.cm` automation file.

In your current configuration, the `add_label_scope_app_frontend_mobile` automation has two conditions:

```yaml
add_label_scope_app_frontend_mobile:
  if:
    - {{ is.scope.apps.frontend_mobile }}
    - {{ pr.labels | match(term=constants.labels.scope.apps.frontend_mobile) | nope }}
  run:
    - action: add-label@v1
      args:
        label: "{{ constants.labels.scope.apps.frontend_mobile }}"
```

When both conditions are true, a new label is added. However, if gitStream is triggered again for any reason, the conditions are evaluated again. Now, the second condition `{{ pr.labels | match(term=constants.labels.scope.apps.frontend_mobile) | nope }}` will be false, causing gitStream to remove the label. This results in the label being added and removed repeatedly.

To resolve this, you should let gitStream manage the labels by having just a single condition:

```yaml
add_label_scope_app_frontend_mobile:
  if:
    - {{ is.scope.apps.frontend_mobile }}
  run:
    - action: add-label@v1
      args:
        label: "{{ constants.labels.scope.apps.frontend_mobile }}"
```

With this configuration, gitStream will add the label if the condition is true, and it won't remove the label if the condition becomes false later.

I hope this helps! Let us know if you have any other questions or concerns.

In addition, for approving gitStream -- you should remove the below as gitStream handles rules changes in a different way, read here: [config.admin.users](https://docs.gitstream.cm/cm-file/#configadminusers)
```
# Automatically approve changes to certain files
  safe_changes:
    if:
      - {{ files | match(list=['.cm/.gitstream.cm']) | every }}
    # approve the PR and explain why
    run: 
      - action: approve@v1
      - action: add-comment@v1
        args:
          comment: |
            This PR is considered a safe change and has been automatically approved.
```
