### ISSUE TITLE
Is there a way to add a comment in the PR when auto-merge is disabled?

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#22]
**Is your feature request related to a problem? Please describe.**

GitHub provides contributors an option to [auto-merge](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository) when all merge requirements are met (e.g., At least X approvals, no unresolved conversations, all checks passed, etc).
However, anyone opening a PR must actively enable the option to auto-merge a PR.
Chasing developers to make sure they enabled auto-merge on their PRs can be very frustrating. :angry: 

**Describe the solution you'd like**

We would like an option add a comment in the PR reminding the developer to enable auto-merge only if it is not already enabled.
It would be nice if the `pr` context variable will have a boolean member called `auto_merge`.
This way we can create a new automation as follows:

```yaml
automations:
  enable_auto_merge:
    if: 
      - {{ not pr.auto_merge }}
    run:
      - action: add-comment@v1
        args:
          comment: |
            Don't forget to enable auto-merge.
```

**Describe alternatives you've considered**

We thought about creating workflow that is triggered on PR synchronize event to add this comment when auto-merge is disabled for the PR in context.
But, that would spam the PR with the same comment multiple times (every time it is synchronized). :slightly_frowning_face:
