### ISSUE TITLE
`merge` action is skipped instead of waiting for required checks to pass

### ISSUE THREAD

**Issue by KnutZuidema** [linear-b/gitstream#228]
We are using an automation to merge @dependabot PRs, as described in the [Dependabot integration documentation](https://docs.gitstream.cm/integrations/dependabot/). However, the action to merge the PR is skipped with the message: 
> Waiting for required checks and approvals, details: Required status check "<redacted>" is pending. You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.

I would expect the `merge` action to wait for all checks to pass, before attempting to merge the PR.

**Comment by vim-zz** [comment]
@KnutZuidema did you try setting `wait_for_all_checks: true` -- see here: https://docs.gitstream.cm/automation-actions/#merge

**Comment by KnutZuidema** [comment]
@vim-zz yes, it's set. I am using the same configuration as is proposed in the Dependabot integration:
```yaml
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  approve_dependabot:
    if:
      - {{ branch.name | includes(term="dependabot") }}
      - {{ branch.author | includes(term="dependabot") }}
    run:
      - action: approve@v1
      - action: add-label@v1
        args:
          label: "approved-dependabot"
      - action: merge@v1
        args:
          wait_for_all_checks: true
          squash_on_merge: true

```
