### ISSUE TITLE
Use looping templates to produce multiline strings

### ISSUE THREAD

**Issue by tresat** [linear-b/gitstream#235]
**Is your feature request related to a problem? Please describe.**
I'd like to loop through a list of element to build a string to use in a comment.

Something like:

```yaml
changes_summary:
  All changes by platform
  {% for platform in changes %}
  Platform {{ platform.name }} - {{ platform.count }} files ({{ (platform.count / changes.total * 100) | round(2) }}% of the total).
  {% endfor %}
```

but when I then try to print this string in a comment like:

```
  # Print a comment breaking down change % by platform
  comment_changes_by_platform:
    if:
      - {{ author.using_gitstream }}
    run:
      - action: add-comment@v1
        args:
          comment: {{ changes_summary }}
```

The result is always something:

```
change_categories/comment_changes_by_platform

• add comment All changes by platform
```

Where the prefix is added, but the looping content is ignored.

**Describe the solution you'd like**
I'd like to know if this is possible, and see an example in the automations library if it is.

**Describe alternatives you've considered**
I've tried various ways to construct multiline strings in yaml as [suggested here](https://yaml-multiline.info/).  None seem to work in combination with the template syntax.

**Comment by BenLloydPearson** [comment]
I'm closing this issue because it should be resolved, please feel free to re-open it if you continue to have issues.

**Comment by tresat** [comment]
I don't think this is fixed.

I'm trying this code:

```
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  summary_table:
    if:
      - {{ true }}
    run:
      - action: add-comment@v1
        args:
          comment: | 
            {{ single }}
            
platforms:
  - ide:
    name: 'ide'
    subprojects:
      - 'platforms/ide/'
  - jvm:
    name: 'jvm'
    subprojects:
      - 'platforms/jvm/'
      - 'subprojects/plugins/'

single: |
  'just some text'

summary: | 
  Platforms
  {% for platform in platforms %}
  {{ platform.name }}
  {% endfor %}
  Footer
``

Against [this](https://github.com/tresat/test-git-stream/pull/53) PR.

If I have the comment print `single`, it works.  If I replace `single` with `summary`, the comment is an empty string.  If I copy the contents of `summary` into the action directly:

```
automations:
  summary_table:
    if:
      - {{ true }}
    run:
      - action: add-comment@v1
        args:
          comment: | 
            Platforms
            {% for platform in platforms %}
            {{ platform.name }}
            {% endfor %}
            Footer
```

Then it also works.  

If I try:

```
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  summary_table:
    if:
      - {{ true }}
    run:
      - action: add-comment@v1
        args:
          comment: | 
            {{ double }}

single: |
  'just some text'

double: |
  'heres one line'
  'and the next'
```

This is also an empty comment for me.

Should I be using a different syntax here?

**Comment by PavelLinearB** [comment]
Thanks, @tresat. I've re-opened the issue and continue with the investigation. Will update here on any developments

**Comment by PavelLinearB** [comment]
Hi @tresat 
I have tested both scenarios here:
https://github.com/PavelLinearB/gitStream-tests/pull/2
using this `cm`:
https://github.com/PavelLinearB/gitStream-tests/blob/main/.cm/gitstream.cm

```   
list_comment:
    if:
      - true
    run:
      - action: add-comment@v1
        args:
          comment: {{ list_summary }}

  double_comment:
    if:
      - {{ true }}
    run:
      - action: add-comment@v1
        args:
          comment: | 
            {{ double }}

double: |
  'heres one line'
  'and the next'

list_summary: 
  prefix
  {% for item in list %}
  name {{ item.name }} - count {{ item.count }}.
  {% endfor %}
  suffix

list:
  - name: aaaaa
    count: 2
  - name: bbbb
    count: 3
  - name: cccc
    count: 4
```

Which successfully added the multiline comments.

Please note: These changes have not been introduced to the playground yet. Thus, running the automations in the playground will result in an empty comment
