### ISSUE TITLE
Enable filtering code reviewers based on team

### ISSUE THREAD

**Issue by atomfinger** [linear-b/gitstream#25]
**Is your feature request related to a problem? Please describe.**
As an organization, we have multiple GitHub teams that are responsible for various repositories. These teams are not necessarily fixed, so members split out into new teams and so forth. We handle this in technical terms by placing them on new GH teams.

The issue is that they are still contributors to the codebase, and they're still a part of the organization, which means that they'll likely to be assigned as code reviewers for teams they're no longer part of. Today's solution needs us to manually map their GH users to "null", but that means we have to go through our repositories and maintain that list. This can quickly become tedious when one works with a solution that has a ton of repositories while allowing teams to be a little dynamic.

**Describe the solution you'd like**
I would like to be able to filter reviewers based on their team.

**Describe alternatives you've considered**
Right now, the only other option I can think of is either to maintain the team member list for every repo, or have a script that updates every repo as time changes.

**Comment by vim-zz** [comment]
@atomfinger can you share you current automation rule?

**Comment by atomfinger** [comment]
It's basically what you have in your tutorial:

```yaml
  the_right_reviewer:
    if:
      - true
    run:
      - action: add-comment@v1
        args:
          comment: |
            {{ repo | explainRankByGitBlame(gt=25) }}
      - action: add-reviewers@v1
        args:
          reviewers: {{ repo | rankByGitBlame(gt=25) }}
```

To then filter out people we need to do something like this:
```yaml
config:
  user_mapping:
    - 'user that is part of team': 'atomfinger'
    - 'user that is no longer in team': null
```
