### ISSUE TITLE
Old labels are not being removed

### ISSUE THREAD

**Issue by matthewparavati** [linear-b/gitstream#298]
**Describe the bug**

A label that does not meet an automation condition is not getting removed

This was working correctly as of last Friday (8/25) and we haven't made changes to our `gitstream.cm` on Friday or today.

**To Reproduce**

1. Has been reproduced with this automation
```
unresolved_threads:
    if:
      - {{ pr.status == 'open' }}
      - {{ pr.unresolved_threads > 0 }}
    run:
      - action: add-label@v1
        args:
          label: '🚨 Unresolved comments'
          color: '#EC560D'
```
- We add a comment, the label gets added
- Resolving the thread does not remove the label even though gitstream is running again when it's resolved

the evaluated rule looks like this:
```
"gitstream/unresolved_threads":{"if":[{"passed":true},{"passed":false}],"run":[{"action":"add-label@v1","args":{"label":"🚨 Unresolved comments","color":"#EC560D"}}],"passed":false,"isManagedByTriggers":false,"isTriggered":true,"is_org_level":false,"provider_repository_id":206658465},
```

2. [PR URL](https://github.com/Popmenu/client-app/pull/3603)

**Expected behavior**
When a label doesn't meet the automation condition, it is removed

**Screenshots**
**Another example from some a PR - reproducible behavior with other automations, too**
![Screenshot 2023-08-28 at 19 00 21](https://github.com/linear-b/gitstream/assets/12176557/b3c7bae1-9ec9-421b-800c-cc22d3e2f777)

**Gitstream correctly added the new label but the old one remained**
![Screenshot 2023-08-28 at 19 01 04](https://github.com/linear-b/gitstream/assets/12176557/c5e3498c-16ba-4819-a77d-fd42b73fc2c2)

**Additional context**
