### ISSUE TITLE
Add reviewer only after all checks pass and has no conflicts

### ISSUE THREAD

**Issue by MishaKav** [linear-b/gitstream#3]
**Is your feature request related to a problem? Please describe.**

I'm using the following command `add-reviewers@v1`, as below:
```
  ui_review:
    if:
      - {{ files | match(regex='ui\\/') | some }}
    run:
      - action: add-reviewers@v1
        args:
          reviewers: [MishaKav]
```

**Describe the solution you'd like**

- After PR is open, check if it has conflicts, is so, don't ask for review (I don't want to bother people if my PR is still not ready)
- Add reviewer only after all `checks` are passed (I don't want to bother people if my PR is still not ready, and some of my tests are still fail)

**Describe alternatives you've considered**
- For now, I'm waiting for `gitstream` to finish, remove the reviewers manually, fix my PR, push and wait again.

**Additional context**
It may be done via additional properties (maybe names may be better), or should be as `default` IMHO.
```
  ui_review:
    if:
      - {{ files | match(regex='ui\\/') | some }}
    run:
      - action: add-reviewers@v1
        args:
          reviewers: [MishaKav]
          pass-all-checks: true
          has-no-conflicts: true
```

**Comment by yakirm-cr** [comment]
There is another option.
GitHub provides an option to open a PR in draft mode:
![image](https://user-images.githubusercontent.com/86773995/220424861-650fecb7-660d-474a-a96e-8e7f9dffed27.png)

Draft pull requests cannot be merged, and code owners/reviewers are not automatically requested to review draft pull requests.
Checks defined for PRs are executed even for draft PRs.

Once you are ready, [you can mark the PR as "ready for review"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request).

**Comment by MishaKav** [comment]
Thanks @yakirm-cr, I know about `draft PR` option, but it doesn't fit for our usage.
We don't run almost any workflow in draft mode, including `e2e`,  `gitstream` etc. 
** By default `gitsream` is running on `draft PRs`

**Comment by MishaKav** [comment]
Another reminder for this feature, It's similar to this one (that you already have)

```yaml
- action: merge@v1
  args:
    wait_for_all_checks: true
```
