### ISSUE TITLE
gitStream check does not reflect failure when Github Action fails.

### ISSUE THREAD

**Issue by jressey** [linear-b/gitstream#30]
**Describe the bug**

gitStream job is hanging although it appears the job has failed.

**To Reproduce**

We added gitStream to the repo according to instructions earlier in the day. This PR was a typical change to the repo involving business logic.

1. .cm file:
```
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "~{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}

calc:
  etr: {{ branch | estimatedReviewTime }}
is:
  formatting: {{ source.diff.files | isFormattingChange }}
  docs: {{ files | allDocs }}
  tests: {{ files | allTests }}
```
2. PR url: https://github.com/Popmenu/popship/pull/153
3. There are no changes relevant to gitStream
4. 0acbaad346ddf08ba2638f5ef032648d60d19d34

**Expected behavior**

Success or failure are reported for the gitStream job.

**Screenshots**

![image](https://user-images.githubusercontent.com/4954363/223506408-5bb39fe4-eec3-4456-b9d3-95721d5300de.png)

**Additional context**

It is possible that this build was happening during the setup of gitStream for the same repo.
