### ISSUE TITLE
Workflow automation is failing randomly on the "Evaluate rules" step

### ISSUE THREAD

**Issue by floernoult** [linear-b/gitstream#312]
**Describe the bug**
Hi,
We've configured Gitstream on our repo with only one automation taken from the examples : `estimated_time_to_review` 
The Github action itself is an exact copy of the website examples, with only a very light change to filter our bot.

What's strange is that it seems the action is run several times on every PR, even if on the PR you can only see it once in the list.
On the action itself, you can see the runs that are launched:
<img width="532" alt="Capture d’écran 2023-09-07 à 17 00 18" src="https://github.com/linear-b/gitstream/assets/1006512/7052a433-c3e4-4817-b5db-4a1d3d3c8d37">

But on the PR, you see one occurence in the checklist:
<img width="827" alt="Capture d’écran 2023-09-07 à 17 07 44" src="https://github.com/linear-b/gitstream/assets/1006512/0b299f62-4417-4eea-892d-90731d8c09ec">

And sometimes they all pass, sometimes they almost all fail.
Let me know if you need anything else.
Thanks

**To Reproduce**

1. The `.cm` automation file
```
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action : add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}

calc:
  etr: {{ branch | estimatedReviewTime }}
```

2. The PR URL (as it contains the repo and PR identifiers)
--> A recent example is https://github.com/agorapulse/platform/pull/29457

3. Describe your PR relevant content 
--> This PR contains only backend code (dependencies update), but we're having the issue with any kind of PRs (containing frontend code, backend code, tests, refactorings, etc..)

**Expected behavior**

We expect the action to be run only once per PR and to pass, especially since the tag with the estimated time to review is correctly applied.

**Screenshots**
<img width="1336" alt="Capture d’écran 2023-09-07 à 16 55 27" src="https://github.com/linear-b/gitstream/assets/1006512/2a5ae197-50ac-4d37-be01-5b06006c31da">
<img width="748" alt="Capture d’écran 2023-09-07 à 16 55 52" src="https://github.com/linear-b/gitstream/assets/1006512/58e51aaa-91aa-4fed-ae09-afe2f966785f">
