### ISSUE TITLE
Import YAML files with common configuration into .cm files

### ISSUE THREAD

**Issue by korya** [linear-b/gitstream#326]
First of all, thanks guys for the great project! I really like it.

I am sharing a question that I have. I am not sure if it is already possible, the documentation is not very clear about it and no idea if there is a better place to ask such questions. So I am submitting it as a feature request.

I would like to have the ability to share some common logic between `.cm` files. It makes sense for this common configuration to be a regular YAML file. Maybe, if it is a `.cm` it would be even better because then one would be able to share non-trivial logic there.

What I have in my mind is something as follows:

```yaml
# colors.yml
colors:
  danger:  #f64b3b
  warning: #f6803b
  success: #3bf692
```

```yaml
manifest:
  version: 1.0

automations:
  safe_changes:
    if: <...>
    run:
      - action: add-label@v1
        args:
          label: 'cm: LABEL'
          color: {{ colors.danger }}

{% from "colors.yml" import colors %}
```

Is it possible today? If not, is it on your roadmap? If not, what is the suggested way for sharing common configuration?
