### ISSUE TITLE
Error in .cm/gitstream.cm - undefined

### ISSUE THREAD

**Issue by shaynekasai** [linear-b/gitstream#456]
**Describe the bug**

Upon installation of Gitstream we get the following error: 

`Error in .cm/gitstream.cm - undefined`

**To Reproduce**

We installed gitstream, both .cm/gitstream.cm and .github/workflows/gitstream.yml, and we also have it configured GitStream in our GitHub. We see it running however, we get a syntax error 

both cm and yml files are verbatim from the documentation and merged into master

**Expected behavior**

Ideally we would see the regular output of Gitstream or at least better error output to debug the issue

**Comment by vim-zz** [comment]
Hi @shaynekasai, please share the GitHub action log, or at least it's end where the error is presented. 

One reason I can think of, is that something in your tooling changed files content, see: [troubleshooting](https://docs.gitstream.cm/troubleshooting/#gitstream-fails-with-syntax-error-after-adding-new-rules) -- to be on the safe side, use a simple tool like notepad or the builtin GitHub editor, and copy the source files again.

**Comment by shaynekasai** [comment]
Awesome thanks for responding so quickly

```
warning: refname 'upstream/diana/test-branch' is ambiguous.
warning: refname 'upstream/diana/test-branch' is ambiguous.
warning: refname 'upstream/diana/test-branch' is ambiguous.
Already on 'upstream/diana/test-branch'
warning: refname '@{-1}' is ambiguous.
Already on 'upstream/diana/test-branch'
warning: refname 'upstream/diana/test-branch' is ambiguous.
Failed while parsing CM file, to extract CM config
Error: {
  "message": "Error in .cm/gitstream.cm - undefined",
  "owner": "retreatguru",
  "repo": "programs",
  "branch": "diana/test-branch"
}
Error: Process completed with exit code 60.
```

The config is cut and pasted from the 'Label and Approve Simple Changes' example 

```
# -*- mode: yaml -*-
manifest:
  version: 1.0

automations:
  safe_changes:
    if:
      - {{ is.docs or is.tests or is.asset or is.formatting }}
    run: 
      - action: add-label@v1
        args:
          label: 'safe-changes'
      - action: approve@v1
is:
  docs: {{ files | allDocs }}
  tests: {{ files | allTests }}
  asset: {{ files | match(regex=r/\.(png|svg|gif|css)$/) | every }}
  formatting: {{ source.diff.files | isFormattingChange }}
```

Checked for whitespace issues - the other examples on the site def had syntax issues - the above example was the only one that the yq didn't complain about when I ran it through.
