### ISSUE TITLE
Extra backtick causing format issues in dry run output

### ISSUE THREAD

**Issue by michaeldrotar** [linear-b/gitstream#46]
**Describe the bug**

There's an extra backtick here:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/820263/224717172-17f21fa4-13c6-4dc5-9f12-08eb0943b1a2.png">
which misformats here
<img width="369" alt="image" src="https://user-images.githubusercontent.com/820263/224717284-adbb1797-c29f-4bdc-aa8a-2e9c7a75c862.png">
it should render like this
> - to add the following reviewers `johnlock`

**To Reproduce**

- I'm using this automation
```yaml
  assign_previous_contributors:
    if:
      - {{ not pr.draft }}
    run:
      - action: add-comment@v1
        args:
          comment: |
            {{ repo | explainRankByGitBlame(gt=25) | dump | safe }}
      - action: add-reviewers@v1
        args:
          reviewers: {{ repo | rankByGitBlame(gt=25) }}
```
- and then running it in dry mode

**Expected behavior**

it should output without the extra backtick so it renders like this
> - to add the following reviewers `johnlock`

**Screenshots**

**Additional context**
