### ISSUE TITLE
Missing `automations` keyword in *.cm

### ISSUE THREAD

**Issue by SiviP-Glossai** [linear-b/gitstream#51]
**Describe the bug**

Running the github action produces the following error:
```
.cm/gitstream.cm
Missing automations keyword in *.cm
```

**To Reproduce**

1. The `.cm` automation file
```
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}

  safe_changes:
    if:
      - {{ is.formatting or is.docs  }}
    run: 
      - action: add-label@v1
        args:
          label: 'safe-changes'
      - action: approve@v1

calc:
  etr: {{ branch | estimatedReviewTime }}
is:
  formatting: {{ source.diff.files | isFormattingChange }}
  docs: {{ files | allDocs }}
```
2. The PR URL (as it contains the repo and PR identifiers)
https://github.com/Glossai/Production/pull/824

3. Describe your PR relevant content 
It happens in all of our PRs, this is just 1 example

4. Add relevant commit SHA

**Expected behavior**

We do have `automations` keyword so there just should not be an error

**Screenshots**

![image](https://user-images.githubusercontent.com/93525292/225258803-f7912cf0-4516-4060-a4b6-cf885904accd.png)
