### ISSUE TITLE
`pr.reviewers` always returns empty list when configured in cm repo

### ISSUE THREAD

**Issue by bartkuzio** [linear-b/gitstream#516]
**Issue description**

I have the following automation in my `gitstream.cm` file in `cm` repo:
```
  label_missing_reviewers:
    if:
      - {{ pr.reviewers | length < 2 }}
    run:
      - action: add-label@v1
        args:
          label: "⚠️ missing reviewers"
          color: "#008672"
      - action: add-comment@v1
        args:
          comment: "Reviewers count: {{ pr.reviewers | length }}"
```

When running this automation on any PR it always adds the label and the comment says Reviewers count: 0 no matter how many reviewers are added.
The same automation added on a specific repository works fine, so the issue is with the organization wide automation.

I cannot show the PR as it's in a private repo.

**Expected behavior**

`pr.reviewers | length` should return the count of reviewers of the PR.

**Screenshots**
<img width="945" alt="image" src="https://github.com/linear-b/gitstream/assets/121165926/7b205969-596c-46a6-93a2-7d7b76623e7a">

![image](https://github.com/linear-b/gitstream/assets/121165926/e203dab7-f5a0-4100-af59-26a8d725a0e4)
