### ISSUE TITLE
PR title check failing

### ISSUE THREAD

**Issue by bartkuzio** [linear-b/gitstream#521]
**Describe the bug**

PR title check stopped working correctly from today. Most likely `pr.title` has an issue since another check depending on it is also not running. 

**To Reproduce**

I have the following action in `cm` repo:
```
  label_missing_jira_info:
    if:
      - {{ not (has.jira_ticket_in_title or has.no_ref_in_title) }}
    run:
      - action: add-label@v1
        args:
          label: "missing jira"
          color: {{ colors.red }}
      - action: request-changes@v1
        args:
          comment: |
            This PR is missing a Jira ticket reference in the title.
            Please add a Jira ticket reference to the title of this PR or use `NO-REF`.

has:
  jira_ticket_in_title: {{ pr.title | includes(regex=jira.pattern) }}
  no_ref_in_title: {{ pr.title | includes(regex=r/NO-REF/) }}

jira:
  pattern: 'r/\b[A-Za-z]+-\d+\b/'

```

Now each time this action runs it executes the action and requests changes, even if PR title is correct, like 'ABC-123 some title'.
We didn't change the action, it worked correctly last week. 

**Expected behavior**

Action should not execute if PR title matches the regex.

**Screenshots**

![image](https://github.com/linear-b/gitstream/assets/121165926/2566ada6-aab3-49da-8d26-64411e7b8fec)

**Comment by korya** [comment]
I can confirm that we have a similar issue: a rule using regexp matching in PR title and PR description started to fail. It used to work just fine last week.

The config is below:

```yaml
  label_missing_jira_info:
    if:
      - {{ not is.dependabot }}
      - {{ not is.publicRepo }}
      - {{ not (crossref.jiraInTitle and crossref.jiraInDescription) }}
    run:
      - action: add-label@v1
        args:
          label: 'cm: missing-jira'
          color: {{ colors.danger }}
      - action: request-changes@v1
        args:
          comment: |
            This PR is missing a reference to Jira ticket

...

is:
  publicRepo: {{ repo.visibility | match(term='public') }}
  dependabot: {{ (branch.name | includes(term="dependabot")) and (branch.author | includes(term="dependabot")) }}

...

crossref:
  jiraInTitle: {{ pr.title | includes(regex=pattern.jira_ticket_id) }}
  jiraInDescription: {{ pr.description | includes(regex=pattern.jira_ticket_url) }}

pattern:
  jira_ticket_id:     r/\[\s*\w{1,}-\d{1,}(\s+\w{1,}-\d{1,})*\s*\]\s*$/
  jira_ticket_url:    r/-\s+https:\/\/org\.atlassian\.net\/browse\/\w{1,}-\d{1,}\b/
```
