### ISSUE TITLE
Require approvals of certain specific users

### ISSUE THREAD

**Issue by IvanRibakov** [linear-b/gitstream#522]
**Is your feature request related to a problem? Please describe.**
I want to enforce following PR review behaviour:
- When PR is created, all team members are added as reviewers (Alice, Bob, Charlie and Luke the team leader)
- In order for PR to able mergeable, I want the following criteria to be satisfied
   - PR must have at least 2 approvals
   - PR must be approved by Luke the team leader

**Describe the solution you'd like**
I'd like to be able to optionally specify a list of users who's approval is mandatory via `set-required-approvals` action.

**Describe alternatives you've considered**
Github's Code Owners feature seems to give the closest result via "Branch protection" > "Require a pull request before merging" > "Require review from Code Owners". My problem with that is that we're actually trying to substitute Code Owners with gitStream as it is a lot more flexible and allows us to centralize the config at the Org level.

**Comment by vim-zz** [comment]
How about something like this:

```yaml
manifest:
  version: 1.0

automations:
  pr_review:
    if:
      - true
    run:
      - action: add-reviewers@v1
        args:
          reviewers: [acme/team-a]

  pr_merge:
    if:
      - true
    run:
      - action: set-required-approvals@v1
        args:
          approvals: 2
      - action: require-reviewers@v1
        args:
          reviewers: [acme/team-a]
      - action: require-reviewers@v1
        args:
          reviewers: [luke-the-team-lead]
```
