### ISSUE TITLE
Support custom configuration for sharing automations in cm repo

### ISSUE THREAD

**Issue by michaeldrotar** [linear-b/gitstream#56]
**Is your feature request related to a problem? Please describe.**
We have 20+ repos that would like to share a core set of gitstream automations, but certain repos may not need one or two or may need some of them configured slightly differently.

It would be awesome if in addition to the built-in `config` properties if custom properties could also be supported

**Describe the solution you'd like**
I think an easy and flexible solution would be to parse out the `cm` repo's `gitstream.cm` file and then merge it with the local repo's `gitstream.cm` file - so same-named keys would replace each other and arrays would concat together

ex:

```yaml
# cm/.cm/gitstream.cm

automations:
  label_new_contributors:
    if:
      - {{ repo.author_age < setting.new_contributor_days and (repo.age - repo.author_age) >= setting.new_contributor_days }}
    run:
      - action: add-label@v1
        args:
          label: 'new-contibutor'
          color: {{ color.purple }}

color:
  purple: FF00FF

setting:
  new_contributor_days: 14
```

```yaml
# myrepo/.cm/gitstream.cm

automations:
  assign_team_members:
    if:
      - {{ not pr.draft }}
    run:
      - action: add-reviewers@v1
        args:
          team_reviewers: {{ pr.author_teams }}

setting:
  new_contributor_days: 30
```

would result in processing this:
```yaml
automations:
  label_new_contributors:
    if:
      - {{ repo.author_age < setting.new_contributor_days and (repo.age - repo.author_age) >= setting.new_contributor_days }}
    run:
      - action: add-label@v1
        args:
          label: 'new-contibutor'
          color: {{ color.purple }}
  assign_team_members:
    if:
      - {{ not pr.draft }}
    run:
      - action: add-reviewers@v1
        args:
          team_reviewers: {{ pr.author_teams }}

color:
  purple: FF00FF

setting:
  new_contributor_days: 30
```

**Describe alternatives you've considered**
maybe there could be a special `config.custom` key and only that's copied over if it's easier
```yaml
config:
  custom:
    color:
      purple: FF00FF
    new_contributor_days: 30
```

Ofer also mentioned the `cm` repo could do something with `repo.name` to define per-repo customizations in there - that's an okay solution too. It would probably get complex if 20 different repos all needed their own different value
```yaml
setting:
  new_contributor_days: {{ 30 if repo.name === 'myrepo' else 14 }}
```

**Additional context**
This could get complex when dealing with multiple `*.cm` files and how to match up what goes where - I'm not sure I entirely understand the need/purpose of multiples. It might also be nice though if just all cm files were combined together so someone could define each automation in its own `.cm` file and then have another file that's just the custom configuration for all of them. And it could error if the same thing is defined in 2 places in the same repo.
