### ISSUE TITLE
When setting a team through require-reviewers plugin can we have it where we can set the required approvals for that team (or per team)

### ISSUE THREAD

**Issue by clemyp** [linear-b/gitstream#605]
**Describe the bug**

We would like 1 person from each team to check the PR, currently this check can be bypassed if 2 members from 1 team approve.

**To Reproduce**

1. 2 people from the same team can approve. it then bypasses the other team to approve!

**Expected behavior**

Approver from each team required

**Screenshots**

**example setup**
team_review_required:
if:
- {{ files | match(list=code_paths) | some }}
run:
- action: add-reviewers@v1
args:
reviewers: [team-platform-engineering, team-triumph]
- action: set-required-approvals@v1
args:
approvals: 2
- action: add-comment@v1
args:
comment: |
This PR affects the Azure Firewall rules and requires review from the both teams.

**Comment by vim-zz** [comment]
To ensure that one approval from each team is required, you can set up two sequential (cascading) actions where each action specifies a distinct requirement for each team’s approval. Here’s how you could configure it:

```
team_review_required:
  if:
    - {{ files | match(list=code_paths) | some }}
  run:
    - action: add-comment@v1
      args:
        comment: |
          This PR affects the Azure Firewall rules and requires review from the both teams.
    # Ask for review by both teams
    - action: add-reviewers@v1
      args:
        reviewers: [team-platform-engineering, team-triumph] 
    # Make sure 1st team has reviewed and approved
    - action: require-reviewers@v1
      args:
        reviewers: [team-platform-engineering]
    # Make sure 2nd team has reviewed and approved
    - action: require-reviewers@v1
      args:
        reviewers: [team-triumph]

```
