### ISSUE TITLE
Waiting for the previous workflow to finish

### ISSUE THREAD

**Issue by JoeHutchinson** [linear-b/gitstream#614]
**Describe the bug**

I have a `run-github-workflow@1` configuration defined in cm repository, it should trigger a workflow in the `actions` repository in the same organization. When I make a change in a repository named `test` I would expect this configuration to trigger the workflow defined in `actions` repository, however its giving me an error `Waiting for the previous workflow to finish`.

**To Reproduce**

1. The `.cm` automation file
```
# -*- mode: yaml -*-
manifest:
  version: 1.0

triggers:
  on: 
    - commit

automations:
  add_dependabot_config:
    if:
      - true
    run:
      - action: run-github-workflow@v1
        args:
          workflow: add-dependabot/action.yml
          owner: {{repo.owner}}
          repo: actions
          ref: main
          check_name: "add-dependabot"
          stop_ongoing_workflow: false
```
2. The PR URL (as it contains the repo and PR identifiers)
https://github.com/JoeHutchinson/test/pull/9/checks?check_run_id=34029107503
5. Describe your PR relevant content 
Config will evaluate to true regardless of content.
7. Add relevant commit SHA
N/A

**Expected behavior**

Workflow defined in `actions` repository `add-dependabot/action.yml` triggers in the context of the calling repository `test`. 

**Screenshots**

**Additional context**
