### ISSUE TITLE
Slack Notifications Re-running

### ISSUE THREAD

**Issue by tom-moore** [linear-b/gitstream#617]
**Describe the bug**

When using the send-slack-message@v1 action, the notifications are sent every time the gitstream rules re-evaluate which is very noisy. This seems counter to the documentation examples which look like they're designed to run once (e.g. a welcome message to first time PR submitters). 

**To Reproduce**

```
# -*- mode: yaml -*-
# This example configuration for provides basic automations to get started with gitStream.
# View the gitStream quickstart for more examples: https://docs.gitstream.cm/quick-start/
manifest:
  version: 1.0
automations:
  hotfix_notify_slack:
    if:
      - {{ is.hotfix }}
    run:
      - action: send-slack-message@v1
        args:
          message: ":tada: {{ pr.author }} has created a Hotfix PR, '{{ pr.title }}'! Please review at https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ pr.number }} <!here>"
          webhook_url: "{{ env.GITSTREAM_SLACK_DEVLEADERSHIP }}"
  
is:
  formatting: {{ source.diff.files | isFormattingChange }}
  docs: {{ files | allDocs }}
  tests: {{ files | allTests }}
  hotfix: {{ branch.name | match(regex=r/hotfix.*/) }}
```

**Expected behavior**

The notification is only posted once when first run.

**Screenshots**

![image](https://github.com/user-attachments/assets/77a68f77-0abb-409b-beac-ef87d2053aa7)

**Additional context**

As posted here, we are also seeing an issue where team approvals are re-requested/re-added which may be related.
https://github.com/linear-b/gitstream/issues/403#issuecomment-2489154501
