### ISSUE TITLE
new gitstream action for threads (GitLab)

### ISSUE THREAD

**Issue by mcintoshk** [linear-b/gitstream#66]
**Is your feature request related to a problem? Please describe.**
When making changes to some files it is occasionally missed that they didn't also update code in another file. We would like to automate and prevent the merge request from going through until they make sure the files are missed and automate doing so.

**Describe the solution you'd like**
We would like to create threads in GitLab (they block merge requests) when a user makes changes to certain files so it can be used like a task/checklist item.

**Comment by mcintoshk** [comment]
What you proposed seems like it would work.  

An easy example of how we could/would like to use it would be to replace/augment this by creating a thread saying missing tests.

```
if:
  - {{ files | match(regex=r/(test|spec)/) | nope }}
run:
  - action: add-label@v1
    args:
      label: 'missing-tests'
      color: '#E94637'
```
