### ISSUE TITLE
Gitstream Failing to Re-run on Large PRs

### ISSUE THREAD

**Issue by AndreCeridian** [linear-b/gitstream#679]
**Describe the bug**

When a PR is initially submitted the Gitstream action runs OK. If more changes are pushed to the PR, Gitstream will not re-run, it just shows 1 skipped check " gitStream workflow file not found". 

**To Reproduce**

As stated above, this happens when pushing new changes to a PR. I've noticed that it only happens on larger PRs which we have displayed as:
````
estimated_time_to_review:
    if:
      - true
    run:
      - action: add-label@v1
        args:
          label: "{{ calc.etr }} min review"
          color: {{ 'E94637' if (calc.etr >= 20) else ('FBBD10' if (calc.etr >= 5) else '36A853') }}
complex_review:
    if:
      - {{ branch | estimatedReviewTime >= 30 }}
      - {{ files | length >= 10 }}
    run:
      - action: add-label@v1
        args: 
          label: {{ 'complex - 2 approvals needed' if (approvals.zero) }}
          color: '#73067C'
      - action: add-label@v1
        args: 
          label: {{  'complex - 1 approval needed' if (approvals.one) }}
          color: '#73067C'
      - action: add-label@v1
        args: 
          label: {{  'complex' if (approvals.gtOne) }}
          color: '#73067C'
      - action: set-required-approvals@v1
        args:
          approvals: 2
      - action: add-reviewers@v1
        args:
          reviewers: [ReviewerName]
calc:
  etr: {{ branch | estimatedReviewTime }}
approvals:
  zero: {{ pr.approvals | length == 0 }}
  one: {{ pr.approvals | length == 1 }}
  gtZero: {{ pr.approvals | length > 0 }}
  gtOne: {{ pr.approvals | length > 1 }}
  ltTwo: {{ pr.approvals | length < 2 }}
````
This adds a review time estimate, and will set the required reviewers to 2. Then when re-run, would change the label to say only one more reviewer required (if it already has 1 approval).   

**Expected behavior**

Each time a change is submitted to a PR, Gitstream should re-run. I can see the action triggers, but it says the workflow file can't be found.
