### ISSUE TITLE
Incorrect link with Link-JIRA Automation Rule

### ISSUE THREAD

**Issue by rjop-hccgt** [linear-b/gitstream#699]
**Describe the bug**

When using the link-jira automation rule, the link is incorrect.

**To Reproduce**

1. The `.cm` automation file
```yaml
manifest:
  version: 1.0

triggers:
  on:
    - pr_created
    - commit

provider: jira
orgName: <myorg>
{% set ticketid = "" %}
{% for ticket in tickets %}
{% if (ticket | includes(regex=r/.+/)) %}
{% set ticketid = ticket %}
{% endif %}
{% endfor %}
automations:
  link_jira:
    if:
      - {{ is.approved_author }}
      - {{ has.jira_ticket_in_title or has.jira_ticket_in_branch  }}
    run:
      - action: add-comment@v1
        args:
          comment: Issue Tracker Link - [{{ticketid}}]({{tracker[provider].baseurl}}{{ticketid}})
has:
  jira_ticket_in_title: {{ pr.title | includes(regex=r/\b[A-Za-z]+-\d+\b/) }}
  jira_ticket_in_desc: {{ pr.description | includes(regex=r/atlassian.net\/browse\/\w{1,}-\d{3,4}/) }}
  jira_ticket_in_branch: {{ branch.name | includes(regex=tracker[provider].pattern) }}
is:
  approved_author: {{ pr.author | match(list=[ 'github-actions', 'dependabot', '[bot]']) | nope }}
tracker:
  jira:
    baseurl: https://[orgName].atlassian.net/browse/
    pattern: r/\b[A-Za-z]+-\d+\b/
```
3. The PR URL (as it contains the repo and PR identifiers)
The PR is used with the following branch:
feature/MP-1400
5. Describe your PR relevant content 
The PR description is being generated by the `linearb_ai_description` automation rule
7. Add relevant commit SHA**Expected behavior**
I would expect the link url be `<a href="https://myorg.atlassian.net/browse/MP-1400" rel="nofollow">MP-1400</a>`

**Screenshots**

![Image](https://github.com/user-attachments/assets/60e6b07d-eaee-4814-818f-6c706167a4d5)

**Additional context**

**Comment by rjop-hccgt** [comment]
worth mentioning that I've tried changing this
```yaml
tracker:
  jira:
    baseurl: https://[orgName].atlassian.net/browse/
    pattern: r/\b[A-Za-z]+-\d+\b/
```
to
```yaml
tracker:
  jira:
    baseurl: https://myorg.atlassian.net/browse/
    pattern: r/\b[A-Za-z]+-\d+\b/
```
And the link doesn't appear with this change
