### ISSUE TITLE
AI Code Review encountering error when attempting to execute

### ISSUE THREAD

**Issue by beyers-luno** [linear-b/gitstream#736]
**Describe the bug**

We use GitLab for our private repositories. Our rules engine is at version 1.0.80.

The following file has been added to our repo to trigger AI code review: `.cm/code-review.cm` (See below).

When GitStream is triggered to run on a new MR, it outputs the following:
```
    "code-review/linearb_ai_review": {
        "if": [
            {
                "passed": true
            },
            {
                "passed": true
            }
        ],
        "run": [
            {
                "action": "code-review@v1",
                "args": {
                    "error": "Error in calling LinearB_AI service"
                }
            }
        ],
        "passed": true,
        "isManagedByTriggers": false,
        "isTriggered": true,
        "is_org_level": false,
        "cmPath": ".cm/code-review.cm"
    },
```

The only other error logs seem related to analytics:
```
Failed sending logs to datadog: {
  error: AxiosError: Request failed with status code 502
```
The following errors were also encountered:
```
Error in .cm/code-review.cm:
 These arguments are not supported for `code-review@v1`: [guidelines]
```

and
```
{
    "level": "warn",
    "message": "Validator error - ActionsValidator in pr lunomoney/Web/6034",
    "data": {
        "error": "ValidationError: Some args are not supported:  approve_on_LGTM",
```

The `approve_on_LGTM` and `guidelines` arguments were removed to suppress these warnings/errors.

**To Reproduce**

See cm code below.

**Expected behavior**

Expected the AI reviewer API to be called successfully.

**Screenshots**

-

**Additional context**

`code-review.cm`
```
manifest:
  version: 1.0

automations:
  linearb_ai_review:
    if:
      - {{ not pr.draft }}
      - {{ pr.author | match(list=['@project_35771297_bot_558e119f0f4d33f2fc8b315e66d53c86', '@group_14117954_bot_085a90599cd4653c9aa736ce6538ae23', '@project_35771297_bot_3baa505335b81595ea1f502563700a41']) | nope }}
    run:
      - action: code-review@v1
```
