### ISSUE TITLE
set-required-approvals@v1 not blocking PR with no approvals

### ISSUE THREAD

**Issue by emcdaniel-sungage** [linear-b/gitstream#8]
**Describe the bug**

With the referenced gitstream.cm file, at least one reviewer is expected to be added.

```
# -*- mode: yaml -*-

manifest:
  version: 1.0

config:
  ignore_files:
    - 'yarn.lock'
    - 'back-end/server/schema.prisma'
    - 'back-end/server/schema.graphql'
    - 'shared/graphql/generated-types.ts'
is:
  small_pr: '{ branch | estimatedReviewTime <= 5 and files | length <= 20 }'
  medium_or_large_pr: '{ branch | estimatedReviewTime > 5 or files | length > 20 }'

automations:
  single_reviewer:
    if:
      - '{ is.small_pr }'
    run:
      - action: set-required-approvals@v1
        args:
          approvals: 1
  multi_reviewer:
    if:
      - '{ is.medium_or_large_pr }'
    run:
      - action: set-required-approvals@v1
        args:
          approvals: 2
```

**To Reproduce**

It's a private repo so cannot reference PRs or hashes.

**Expected behavior**

With the created PR, which contains only the changes included in the gitstream.cm file, the check should fail as there are no approvals

**Screenshots**

![CleanShot 2023-01-06 at 10 52 23](https://user-images.githubusercontent.com/95384474/211048149-87c582b6-b6b8-4539-9db4-b84ae4acbdf1.png)
