### ISSUE TITLE
Gitstream fails to auto-approve when branch protection is set to require approval of latest push

### ISSUE THREAD

**Issue by ianwesleyarmstrong** [linear-b/gitstream#9]
**Describe the bug**

When `Require approval of the most recent push` is set as a branch protection, gitStream does not re-approve the PR if a previous commit already triggered the approbal

**To Reproduce**

1. The `.cm` automation file
```yaml
# -*- mode: yaml -*-

manifest:
  version: 1.0

automations:
  welcome_message:
    if:
      - {{ repo.contributors | isFirstCommit(branch.author) }}
    run:
      - action: add-comment@v1
        args:
          comment: |
            Welcome @{{ pr.author }}!

  admin_autoapprove:
    if:
      - {{ is.admin }}
    run:
      - action: approve@v1

  review_cicd:
    if:
      - {{ files | match(regex=r/.github\/workflows\/.*\.yml/) | some }}
    run:
      - action: add-reviewers@v1
        args:
          team_reviewers: [infrastructure]

  aws_changes:
    if:
      - {{ is.aws and not is.admin }}
    run:
      - action: add-label@v1
        args:
          label: 'aws'
      - action: add-reviewers@v1
        args:
          team_reviewers: [aws-infrastructure]

  snowflake_changes:
    if:
      - {{ is.snowflake and not is.admin }}
    run:
      - action: add-label@v1
        args:
          label: 'snowflake'
      - action: add-reviewers@v1
        args:
          team_reviewers: [snowflake-infrastructure]
is:

  admin: {{ pr.author | includes(list=['ianwesleyarmstrong']) }}

```
3. [The PR URL (as it contains the repo and PR identifiers)](https://github.com/opencareer/tf-infra/pull/123)
4. N/A
5. 28d2c2254fa046dee6c1367c46a1c6c74485e90c

**Expected behavior**

**Screenshots**

**Additional context**
