### ISSUE TITLE
Include additional documentation file format in allDocs filter - asciidoc.

### ISSUE THREAD

**Issue by tresat** [linear-b/gitstream#93]
**Describe the bug**

Changes to documentation in asciidoc format are not caught by the `allDocs` filter.

**To Reproduce**

1. Add an automation that is meant to trigger if `files | allDocs`
2. Add or change a documentation file with an `.adoc` extension
3. The automation does not trigger

**Expected behavior**

The automation should trigger.  Asciidoctor is a popular format for writing documentation.

**Additional context**

Some way to configure what types of files are considered documentation (either on a particular `allDocs` usage, or globally, would be very helpful.  There are sure to be other types of documentation in use not in the current list.

**Comment by vim-zz** [comment]
Thank you for the feedback., `.adoc` files will be added (this is not a bug but a feature request :) )

In the meanwhile you can write it yourself and add `adoc`:
```
  docs:
    if:
      - {{ (files | match(regex=r/.*\.(md|mkdown|txt|rst|adoc)$/) | every) and (files | match(regex=r/requirements\/.*\.txt$/) | nope ) }}
    run:
      - action: add-label@v1
        args:
          label: all-docs
```
