### ISSUE TITLE
null user_mapping is ignored

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#98]
**Describe the bug**
We defined in `.cm/gitstream.cm` a section with `config.user_mapping` as described [here](https://docs.gitstream.cm/cm-file/#configuser_mapping).
Unfortunately, gitStream still tried to add users mapped to `null` as reviewers.
As those users are no longer in the organization, `add-reviewers` job fails (which blocks the PR from being merged). :slightly_frowning_face: 

**To Reproduce**

1. At the bottom of `.cm/gitstream.cm` add the following (replace the user mapped to `null` with a real user):
  ```yaml
  config:
    user_mapping:
      - 'Popeye Man <popeye@invalid.com>': 'popeye-the-salyor-man'
      - 'Popeye Man <popeye2@invalid.com>': 'popeye-the-salyor-man'
      - 'Popeye': null
  ```
2. Create a PR for a files added/modified by the user mapped to `null`.
3. gitStream workflow should start running.

**Expected behavior**
`add-reviewers` job should pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/86773995/232309218-61844ff4-2517-4491-b106-f4559b0d2aa4.png)

**Additional context**
The `add-reviewers` job should NOT attempt to add any other user mapped to `null` as a reviewer.
